// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID      int64       `json:"id"`
	Uuid    pgtype.UUID `json:"uuid"`
	Name    string      `json:"name"`
	UsersID pgtype.Int8 `json:"users_id"`
}

type Expense struct {
	ID         int64              `json:"id"`
	Uuid       pgtype.UUID        `json:"uuid"`
	Title      string             `json:"title"`
	Amount     int32              `json:"amount"`
	Date       pgtype.Timestamptz `json:"date"`
	CategoryID pgtype.Int8        `json:"category_id"`
	UsersID    pgtype.Int8        `json:"users_id"`
}

type User struct {
	ID       int64       `json:"id"`
	Uuid     pgtype.UUID `json:"uuid"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
}

type UsersAction struct {
	ID       int64              `json:"id"`
	UsersID  pgtype.Int8        `json:"users_id"`
	Action   string             `json:"action"`
	Type     int32              `json:"type"`
	Ip       string             `json:"ip"`
	Country  string             `json:"country"`
	ActionAt pgtype.Timestamptz `json:"action_at"`
}

type UsersLog struct {
	ID        int64              `json:"id"`
	UsersID   pgtype.Int8        `json:"users_id"`
	OldValue  []byte             `json:"old_value"`
	NewValue  []byte             `json:"new_value"`
	TableName pgtype.Text        `json:"table_name"`
	Type      int32              `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	LogAt     pgtype.Timestamptz `json:"log_at"`
}
