// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (uuid, name, email, password, is_verification)
VALUES ($1, $2, $3, $4, 0)
RETURNING id, uuid, name, email, password, is_verification
`

type CreateUserParams struct {
	Uuid     pgtype.UUID `json:"uuid"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Uuid,
		arg.Name,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsVerification,
	)
	return i, err
}

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO user_verification_code (code, users_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, code, users_id, expires_at, created_at
`

type CreateVerificationCodeParams struct {
	Code      string             `json:"code"`
	UsersID   pgtype.Int8        `json:"users_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (UserVerificationCode, error) {
	row := q.db.QueryRow(ctx, createVerificationCode, arg.Code, arg.UsersID, arg.ExpiresAt)
	var i UserVerificationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UsersID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id, uuid, name, email, password, is_verification
FROM
    users
WHERE
    id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsVerification,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT 
    id, uuid, name, email, password, is_verification 
FROM 
    users
offset $1 limit $2
`

type ListUsersParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.IsVerification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginUser = `-- name: LoginUser :one
SELECT
    id, uuid, name, email, password, is_verification
FROM
    users
WHERE
    email = $1
`

func (q *Queries) LoginUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, loginUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsVerification,
	)
	return i, err
}

const setVerificationStatus = `-- name: SetVerificationStatus :exec
UPDATE users
SET is_verification = $1
WHERE id = $2
`

type SetVerificationStatusParams struct {
	IsVerification bool  `json:"is_verification"`
	ID             int64 `json:"id"`
}

func (q *Queries) SetVerificationStatus(ctx context.Context, arg SetVerificationStatusParams) error {
	_, err := q.db.Exec(ctx, setVerificationStatus, arg.IsVerification, arg.ID)
	return err
}
