// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	CheckUserVerificationCode(ctx context.Context, arg CheckUserVerificationCodeParams) (User, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (UserVerificationCode, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LoginUser(ctx context.Context, email string) (User, error)
	SetVerificationStatus(ctx context.Context, arg SetVerificationStatusParams) error
}

var _ Querier = (*Queries)(nil)
