// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserVerificationCode = `-- name: CheckUserVerificationCode :one
SELECT
    id, uuid, name, email, password, is_verification
FROM
    users u
WHERE
    u.id = $1
    AND u.is_verification = false
    AND EXISTS (
        SELECT 1
        FROM user_verification_code
        WHERE users_id = u.id
          AND code = $2
          AND expires_at > NOW()
    )
`

type CheckUserVerificationCodeParams struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

func (q *Queries) CheckUserVerificationCode(ctx context.Context, arg CheckUserVerificationCodeParams) (User, error) {
	row := q.db.QueryRow(ctx, checkUserVerificationCode, arg.ID, arg.Code)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsVerification,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (uuid, name, email, password, is_verification)
VALUES ($1, $2, $3, $4, false)
RETURNING id, uuid, name, email, password, is_verification
`

type CreateUserParams struct {
	Uuid     pgtype.UUID `json:"uuid"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Uuid,
		arg.Name,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsVerification,
	)
	return i, err
}

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_session (id, user_id, refresh_token, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, refresh_token, created_at, expires_at, is_active
`

type CreateUserSessionParams struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       int32              `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.ID,
		arg.UserID,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO user_verification_code (code, users_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, code, users_id, expires_at, created_at
`

type CreateVerificationCodeParams struct {
	Code      string             `json:"code"`
	UsersID   pgtype.Int8        `json:"users_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (UserVerificationCode, error) {
	row := q.db.QueryRow(ctx, createVerificationCode, arg.Code, arg.UsersID, arg.ExpiresAt)
	var i UserVerificationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UsersID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id, uuid, name, email, password, is_verification
FROM
    users
WHERE
    id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsVerification,
	)
	return i, err
}

const getUserSessionByUserId = `-- name: GetUserSessionByUserId :one
SELECT
    id, user_id, refresh_token, created_at, expires_at, is_active
FROM
    user_session
WHERE
    user_id = $1
    AND is_active = true
`

func (q *Queries) GetUserSessionByUserId(ctx context.Context, userID int32) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByUserId, userID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT 
    id, uuid, name, email, password, is_verification 
FROM 
    users
offset $1 limit $2
`

type ListUsersParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.IsVerification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginUser = `-- name: LoginUser :one
SELECT
    id, uuid, name, email, password, is_verification
FROM
    users
WHERE
    email = $1
`

func (q *Queries) LoginUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, loginUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsVerification,
	)
	return i, err
}

const setVerificationStatus = `-- name: SetVerificationStatus :exec
UPDATE users
SET is_verification = $1
WHERE id = $2
`

type SetVerificationStatusParams struct {
	IsVerification bool  `json:"is_verification"`
	ID             int64 `json:"id"`
}

func (q *Queries) SetVerificationStatus(ctx context.Context, arg SetVerificationStatusParams) error {
	_, err := q.db.Exec(ctx, setVerificationStatus, arg.IsVerification, arg.ID)
	return err
}
